[package]
name = "yugendb"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/yugendb"
description = "User-facing Rust facade crate for yugendb."
keywords.workspace = true
categories.workspace = true
exclude.workspace = true

[features]
default = []
memory = ["dep:yugendb-memory"]
sqlite = ["dep:yugendb-sqlite"]
mysql = ["dep:yugendb-mysql"]
mongodb = ["dep:yugendb-mongodb"]
postgres = ["dep:yugendb-postgres"]
redis = ["dep:yugendb-redis"]
all-drivers = [
    "memory",
    "sqlite",
    "mysql",
    "mongodb",
    "postgres",
    "redis",
]

[dependencies]
yugendb-core = { workspace = true }
yugendb-memory = { workspace = true, optional = true }
yugendb-sqlite = { workspace = true, optional = true }
yugendb-mysql = { workspace = true, optional = true }
yugendb-mongodb = { workspace = true, optional = true }
yugendb-postgres = { workspace = true, optional = true }
yugendb-redis = { workspace = true, optional = true }

[lints]
workspace = true
