[package]
name = "yugendb-memory"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/yugendb-memory"
description = "In-memory yugendb driver for local and test storage."
keywords.workspace = true
categories.workspace = true
exclude.workspace = true

[dependencies]
async-trait.workspace = true
parking_lot.workspace = true
yugendb-core.workspace = true

[dev-dependencies]
serde_json.workspace = true
chrono.workspace = true
serde.workspace = true
tokio.workspace = true

[lints]
workspace = true
